name = "SwagerSMP"
author = "Lith"
version = "1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54c4bc03ab4722c2a2ae9df242eb212daccc7b04db886e2b77a6024a0ab2b60e"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
